### ISSUE TITLE
MIRO Day Counter

### ISSUE THREAD

**Issue by vpbranduk** [mtreinik/miro-day-counter#3]
This plug-in does not appear when I search for it in MIRO Market Place.  Has it been removed or perhaps is it not compatible with a more recent version?

**Comment by mtreinik** [comment]
I am sorry, but the plugin is not at the Miro Marketplace. There was a long delay in publishing the plugin and then Miro asked me to create a Privacy Policy document for the plugin and I lost interest. I have not checked if the plugin would be compatible with the current Miro board. Apologies, but I do not intend to work on the plugin.

**Comment by vpbranduk** [comment]
What a shame

Dr V Paul Brand
Risk Solutions
0161 242 1153
07968 107141
***@***.***
________________________________
